### ISSUE TITLE
Anybody can install / remove packages?

### ISSUE THREAD

**Issue by lilydjwg** [linuxdeepin/lastore-daemon#1]
I tried to call lastore's dbus methods as 'nobody' and it worked! So is this a local privilege escalation bug?

Details:
1. `xhost +` to authorize 'nobody' to use the X display
2. `sudo -u nobody d-feet`, then pick some methods to run

**Comment by snyh** [comment]
This is product owner's decision. 
Any one can install/remove/upgrade packages without enter password.

It's better to verify whether the caller has "sudo privilege".  I think we can do this authentication. 
I will implement this feature before 2015 Final Version. 

Thanks for your caution.

**Comment by lilydjwg** [comment]
System users shouldn't be granted such privileges, because people may run various services. Most desktop users won't care this, but Deepin has a server version, and some people do use the desktop on servers.

You definitely mean to allow a *normal desktop* user to use this privilege, don't you? Even better, allow only a group to use this without authentication, and put all normal desktop users in that group.

Also, there are similar issues with other D-Bus services. Using a group for all these things should be easy and practical.

**Comment by snyh** [comment]
Yes, it's better to make  a group to manager privileges like all other server daemons .

But this need multi-component complete do this. Not all "desktop user" should have this privilege,  only "Admin desktop user" should have.

And I think "sudo" is enough do this.  
https://cr.deepin.io/#/c/9797

**Comment by lilydjwg** [comment]
It's your product, so you decide which "desktop users" should have that privilege.

You are so fast with the commit, but in the config file I noticed something like a typo: `send_send_member`?

**Comment by snyh** [comment]
Luckily this CL hasn't be merged.   
I have fixed the typo after you notice it.
