### ISSUE TITLE
关于SmartMirrors的配置

### ISSUE THREAD

**Issue by panhaitao** [linuxdeepin/lastore-daemon#2]
Acquire::SmartMirrors::Enable true;
是否可以配置为 Enable false;

**Comment by snyh** [comment]
当然可以设置为false. 　　在/etc/apt/apt.conf.d/99lastore.conf 中配置．　
不过关闭后，镜像源的功能就会失效．　(看来需要检测一下这个设置，然后让控制中心给出不同响应了．)
