### ISSUE TITLE
metadata更新错误

### ISSUE THREAD

**Issue by snyh** [linuxdeepin/lastore-daemon#21]
这个文件 /var/lib/lastore/scripts/metadata_remote 的内容好像不对，是写死了cdn.packages.deepin.com? 

另外访问summary.sig的问题，应该是不存在的，lastore-tools里特意加了gpg-verify-no这个参数的

@electricface

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
