### ISSUE TITLE
改进镜像源选择方式

### ISSUE THREAD

**Issue by snyh** [linuxdeepin/lastore-daemon#4]
目前的镜像源方案可以保证数据100%准确. 但在特殊情况下(如官方源刚刚更新)的访问速度不够友好. 
因此通过以下方式改进
- [x] smartmirror尽可能利用多个镜像源.(目前只使用一个用户选择的镜像源) 来进行实时的寻找最优服务器.
- [ ] 控制中心以及后端API接口改进, 镜像源不再是单选(用户自行开启访问速度较好的多个镜像源. 最终使用哪个由程序自行判断)

**Comment by derekdai** [comment]
目前執行 apt-get 的時候會停頓好一陣子 (因為在測速?), 是否能這麼做
* 第一次用 download 的方式測速, 得知 bandwidth 資訊
* 下次改用 ping or tcp sync/ack 的方式確認 latency 即可

**Comment by snyh** [comment]
没有进行测试,也没用进行ping之类的操作. 
目前检测最优服务器的方式是,同时向多个服务器发送deb下载请求来获取最快的服务器.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
