### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by heysion** [linuxdeepin/lastore-daemon#5]
Hi，i test build depends in mipsel platform 
change golang-go for golang-go | gccgo-5 
like  debian/control 
====
Source: lastore-daemon
Section: admin
Priority: extra
Maintainer: Deepin Sysdev <sysdev@deepin.com>
Build-Depends: debhelper (>= 9), pkg-config, golang-go | gccgo-5 ,
 golang-dlib-dev,
 deepin-gettext-tools,

**Comment by snyh** [comment]
tks.
I have issue a CL at  https://cr.deepin.io/#/c/15047/  
Next time you can just request a CL

**Comment by manateelazycat** [comment]
@heysion Can close this issue now?
